'use client';

import React, { useState } from 'react';
import { 
  Calendar as CalendarIcon, 
  ChevronLeft, 
  ChevronRight, 
  Plus, 
  Filter, 
  Eye, 
  CheckCircle, 
  AlertTriangle, 
  Clock, 
  FileText, 
  Send,
  MoreHorizontal,
  X,
  Sparkles
} from 'lucide-react';
import { DashboardShell } from '@/components/layout/DashboardShell';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';

interface ScheduledPost {
  id: string;
  platform: 'LinkedIn' | 'Instagram' | 'Facebook';
  text: string;
  time: string;
  day: number; // Day of August 2026 (e.g. 17 is Aug 17)
  status: 'DRAFT' | 'REVIEW' | 'APPROVED' | 'SCHEDULED' | 'PUBLISHED' | 'FAILED';
  pillar: string;
}

export default function ContentCalendar() {
  const [currentView, setCurrentView] = useState<'month' | 'week'>('month');
  const [platformFilter, setPlatformFilter] = useState<'ALL' | 'LinkedIn' | 'Instagram' | 'Facebook'>('ALL');
  const [statusFilter, setStatusFilter] = useState<'ALL' | 'DRAFT' | 'REVIEW' | 'SCHEDULED' | 'PUBLISHED' | 'FAILED'>('ALL');
  const [selectedPost, setSelectedPost] = useState<ScheduledPost | null>(null);
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
  const [newPostTopic, setNewPostTopic] = useState('');
  const [newPostPlatform, setNewPostPlatform] = useState<'LinkedIn' | 'Instagram' | 'Facebook'>('LinkedIn');

  // August 2026 dates logic (August 1, 2026 is Saturday, so offset is 6 days)
  const daysInMonth = 31;
  const startDayOffset = 6; // Sat
  const totalSlots = 35; // 5 weeks grid

  // Mock scheduled content data
  const [posts, setPosts] = useState<ScheduledPost[]>([
    {
      id: 'post-101',
      platform: 'LinkedIn',
      text: 'Creating high-performing marketing channels doesn’t require a massive budget. It’s about daily consistency.',
      time: '09:00 AM',
      day: 17, // Monday
      status: 'SCHEDULED',
      pillar: 'Educational'
    },
    {
      id: 'post-102',
      platform: 'Instagram',
      text: 'Behind the scenes at Acme Co! Staging our new pour-over kettle setup. Vibe check! ☕',
      time: '02:00 PM',
      day: 17,
      status: 'REVIEW',
      pillar: 'Brand Story'
    },
    {
      id: 'post-103',
      platform: 'Facebook',
      time: '05:00 PM',
      day: 16, // Yesterday
      status: 'PUBLISHED',
      pillar: 'Promotional'
    },
    {
      id: 'post-104',
      platform: 'LinkedIn',
      time: '11:00 AM',
      day: 19, // Wednesday
      status: 'DRAFT',
      pillar: 'Educational'
    },
    {
      id: 'post-105',
      platform: 'Instagram',
      time: '04:00 PM',
      day: 21, // Friday
      status: 'APPROVED',
      pillar: 'Inspirational'
    },
    {
      id: 'post-106',
      platform: 'Facebook',
      time: '10:00 AM',
      day: 21,
      status: 'FAILED',
      pillar: 'Promotional'
    }
  ]);

  // Filter posts
  const filteredPosts = posts.filter(post => {
    const matchPlatform = platformFilter === 'ALL' || post.platform === platformFilter;
    const matchStatus = statusFilter === 'ALL' || post.status === statusFilter;
    return matchPlatform && matchStatus;
  });

  // Fetch posts for specific day of August
  const getPostsForDay = (day: number) => {
    return filteredPosts.filter(post => post.day === day);
  };

  // Status Badge Helper
  const getStatusBadge = (status: string) => {
    const mapping = {
      DRAFT: 'bg-slate-100 text-slate-600 border-slate-200',
      REVIEW: 'bg-amber-50 text-amber-700 border-amber-200',
      APPROVED: 'bg-emerald-50 text-emerald-700 border-emerald-200',
      SCHEDULED: 'bg-blue-50 text-blue-700 border-blue-200',
      PUBLISHED: 'bg-emerald-100 text-emerald-800 border-emerald-300',
      FAILED: 'bg-red-50 text-red-700 border-red-200'
    };
    return mapping[status as keyof typeof mapping] || 'bg-slate-50 text-slate-500';
  };

  // Mock post creation handler
  const handleCreatePost = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newPostTopic) return;

    const newPost: ScheduledPost = {
      id: `post-${Date.now()}`,
      platform: newPostPlatform,
      text: `${newPostTopic} — Generated by Antigravity AI Strategy Assistant. ✨ #AI #SocialMedia`,
      time: '10:00 AM',
      day: 17, // Current day
      status: 'DRAFT',
      pillar: 'Educational'
    };

    setPosts([...posts, newPost]);
    setNewPostTopic('');
    setIsCreateModalOpen(false);
  };

  // Date cell click trigger
  const handleCellClick = (day: number) => {
    if (day > 0 && day <= daysInMonth) {
      setIsCreateModalOpen(true);
    }
  };

  return (
    <DashboardShell title="Content Calendar">
      <div className="space-y-8">

        {/* Toolbar Header Controls */}
        <div className="flex flex-col xl:flex-row justify-between items-start xl:items-center gap-4 bg-white/40 p-5 rounded-2xl border border-slate-200/50 backdrop-blur-md">
          
          {/* Left side filters */}
          <div className="flex flex-wrap items-center gap-3">
            <span className="text-2xs font-extrabold text-slate-400 uppercase tracking-widest flex items-center gap-1.5 mr-2">
              <Filter className="w-3.5 h-3.5" />
              <span>Filters</span>
            </span>
            
            {/* Platform filter */}
            <select
              value={platformFilter}
              onChange={(e) => setPlatformFilter(e.target.value as any)}
              className="px-3.5 py-2 bg-white border border-slate-200 rounded-xl text-xs font-bold text-slate-700 focus:outline-none focus:ring-4 focus:ring-brand-indigo/5 cursor-pointer"
            >
              <option value="ALL">All Platforms</option>
              <option value="LinkedIn">LinkedIn</option>
              <option value="Instagram">Instagram</option>
              <option value="Facebook">Facebook</option>
            </select>

            {/* Status Filter */}
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value as any)}
              className="px-3.5 py-2 bg-white border border-slate-200 rounded-xl text-xs font-bold text-slate-700 focus:outline-none focus:ring-4 focus:ring-brand-indigo/5 cursor-pointer"
            >
              <option value="ALL">All Statuses</option>
              <option value="DRAFT">Draft</option>
              <option value="REVIEW">In Review</option>
              <option value="SCHEDULED">Scheduled</option>
              <option value="PUBLISHED">Published</option>
              <option value="FAILED">Failed</option>
            </select>
          </div>

          {/* Right side navigation & toggle view */}
          <div className="flex flex-wrap items-center gap-3 w-full xl:w-auto justify-between xl:justify-end">
            
            {/* Date Nav Controls */}
            <div className="flex items-center gap-1.5">
              <button className="p-2 bg-white border border-slate-200 rounded-xl text-slate-500 hover:text-slate-800 transition-colors shadow-sm cursor-pointer">
                <ChevronLeft className="w-4 h-4" />
              </button>
              <span className="text-xs font-bold text-slate-700 px-3">August 2026</span>
              <button className="p-2 bg-white border border-slate-200 rounded-xl text-slate-500 hover:text-slate-800 transition-colors shadow-sm cursor-pointer">
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>

            {/* View selectors */}
            <div className="inline-flex rounded-xl bg-slate-100 p-1 border border-slate-200 shadow-inner">
              <button
                onClick={() => setCurrentView('month')}
                className={`px-3 py-1.5 text-2xs font-extrabold rounded-lg transition-colors cursor-pointer ${
                  currentView === 'month' ? 'bg-white text-slate-800 shadow-sm' : 'text-slate-500'
                }`}
              >
                Month View
              </button>
              <button
                onClick={() => setCurrentView('week')}
                className={`px-3 py-1.5 text-2xs font-extrabold rounded-lg transition-colors cursor-pointer ${
                  currentView === 'week' ? 'bg-white text-slate-800 shadow-sm' : 'text-slate-500'
                }`}
              >
                Week View
              </button>
            </div>

            <Button 
              variant="primary" 
              size="sm" 
              className="gap-1.5 shadow-sm"
              onClick={() => setIsCreateModalOpen(true)}
            >
              <Plus className="w-4 h-4" />
              <span>Create Post</span>
            </Button>

          </div>

        </div>

        {/* Calendar Grid Container */}
        <Card hoverEffect={false} className="border border-slate-200/60 bg-white/70 backdrop-blur-md shadow-2xl p-0 rounded-2xl overflow-hidden">
          
          {/* Weekday Labels Header */}
          <div className="grid grid-cols-7 border-b border-slate-100 bg-slate-50/70 py-3.5">
            {['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map(label => (
              <span key={label} className="text-[10px] font-extrabold text-slate-500 uppercase tracking-widest text-center">
                {label}
              </span>
            ))}
          </div>

          {/* Month view calendar grid */}
          <div className="grid grid-cols-7 grid-rows-5 h-[720px] border-slate-100 bg-slate-100/10">
            {Array.from({ length: totalSlots }).map((_, index) => {
              const dayNumber = index - startDayOffset + 1;
              const isValidDay = dayNumber > 0 && dayNumber <= daysInMonth;
              const dayPosts = isValidDay ? getPostsForDay(dayNumber) : [];

              return (
                <div 
                  key={index} 
                  onClick={() => isValidDay && handleCellClick(dayNumber)}
                  className={`border-r border-b border-slate-100/80 p-3.5 flex flex-col gap-2 hover:bg-slate-50/[0.2] transition-colors relative cursor-pointer group ${
                    !isValidDay 
                      ? 'bg-slate-50/40 text-slate-300 cursor-not-allowed' 
                      : dayNumber === 17 
                        ? 'bg-brand-indigo/[0.015] border-brand-indigo/20 ring-1 ring-brand-indigo/10 ring-inset' 
                        : ''
                  }`}
                >
                  {/* Day cell header */}
                  {isValidDay && (
                    <div className="flex justify-between items-center w-full">
                      <span className={`text-[10px] font-extrabold inline-flex items-center justify-center w-6 h-6 rounded-lg ${
                        dayNumber === 17 
                          ? 'gradient-bg text-white shadow-md shadow-brand-indigo/15 font-black' 
                          : 'text-slate-400 group-hover:text-brand-indigo group-hover:bg-brand-indigo/5 transition-colors'
                      }`}>
                        {dayNumber}
                      </span>
                      
                      {/* Plus icon on hover */}
                      <span className="opacity-0 group-hover:opacity-100 transition-opacity duration-200 w-5 h-5 rounded-lg bg-slate-50 text-slate-400 hover:text-brand-indigo hover:bg-brand-indigo/5 flex items-center justify-center border border-slate-200/50 shadow-sm">
                        <Plus className="w-3.5 h-3.5" />
                      </span>
                    </div>
                  )}

                  {/* Day Posts List */}
                  <div className="flex-1 overflow-y-auto no-scrollbar space-y-2 pt-1">
                    {dayPosts.map(post => {
                      const platformColors = {
                        LinkedIn: 'bg-blue-50/70 border-blue-200/60 text-blue-700 hover:border-blue-400',
                        Instagram: 'bg-pink-50/70 border-pink-200/60 text-pink-750 hover:border-pink-400',
                        Facebook: 'bg-sky-50/70 border-sky-200/60 text-sky-700 hover:border-sky-400'
                      };
                      const statusDots = {
                        DRAFT: 'bg-slate-400',
                        REVIEW: 'bg-amber-500 animate-pulse',
                        APPROVED: 'bg-emerald-500',
                        SCHEDULED: 'bg-brand-indigo shadow-[0_0_8px_rgba(79,70,229,0.5)]',
                        PUBLISHED: 'bg-emerald-600',
                        FAILED: 'bg-red-500'
                      };
                      return (
                        <div
                          key={post.id}
                          onClick={(e) => {
                            e.stopPropagation();
                            setSelectedPost(post);
                          }}
                          className={`p-2.5 border rounded-xl shadow-[0_2px_8px_rgba(0,0,0,0.01)] text-left transition-all duration-200 hover:-translate-y-0.5 hover:shadow-md ${
                            platformColors[post.platform]
                          }`}
                        >
                          <div className="flex items-center justify-between gap-1 mb-1.5">
                            <span className="text-[9px] font-extrabold uppercase tracking-wider">{post.platform}</span>
                            <div className="flex items-center gap-1">
                              <span className="text-[9px] font-bold opacity-60">{post.time}</span>
                              <span className={`w-1.5 h-1.5 rounded-full ${statusDots[post.status]}`} title={`Status: ${post.status}`}></span>
                            </div>
                          </div>
                          <p className="text-[10px] leading-relaxed font-semibold line-clamp-2">{post.text}</p>
                        </div>
                      );
                    })}
                  </div>

                </div>
              );
            })}
          </div>

        </Card>

        {/* Selected Post Detail Overlay / Sidebar Drawer */}
        {selectedPost && (
          <div className="fixed inset-0 z-50 flex justify-end">
            <div className="absolute inset-0 bg-slate-900/20 backdrop-blur-sm" onClick={() => setSelectedPost(null)}></div>
            <div className="relative w-full max-w-md bg-white h-full shadow-2xl p-6 flex flex-col justify-between border-l border-slate-200">
              
              {/* Drawer Header */}
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <span className="px-2.5 py-0.5 rounded-lg bg-brand-indigo/10 text-brand-indigo text-2xs font-extrabold border border-brand-indigo/10">
                    {selectedPost.platform} Draft
                  </span>
                  <button 
                    onClick={() => setSelectedPost(null)}
                    className="p-1 rounded-xl bg-slate-50 text-slate-400 hover:text-slate-600 border border-slate-200 cursor-pointer"
                  >
                    <X className="w-4 h-4" />
                  </button>
                </div>
                
                <h3 className="text-base font-extrabold text-slate-800 tracking-tight">Post Details</h3>
                <hr className="border-slate-100" />
                
                {/* Content preview */}
                <div className="space-y-2">
                  <span className="text-[10px] font-extrabold text-slate-400 uppercase tracking-widest block">Generated Copy</span>
                  <p className="text-xs text-slate-700 bg-slate-50 border border-slate-100 rounded-xl p-4 leading-relaxed font-medium">
                    {selectedPost.text}
                  </p>
                </div>

                <div className="grid grid-cols-2 gap-4 text-xs font-semibold text-slate-600">
                  <div className="space-y-1">
                    <span className="text-[10px] font-extrabold text-slate-400 uppercase tracking-widest block">Publish Time</span>
                    <span className="text-slate-700 font-bold block bg-slate-50 p-2.5 rounded-xl border border-slate-100">{selectedPost.time}</span>
                  </div>
                  <div className="space-y-1">
                    <span className="text-[10px] font-extrabold text-slate-400 uppercase tracking-widest block">Status</span>
                    <span className={`inline-block px-3 py-2 rounded-xl border font-bold text-center w-full uppercase text-2xs tracking-wider ${getStatusBadge(selectedPost.status)}`}>
                      {selectedPost.status}
                    </span>
                  </div>
                </div>
              </div>

              {/* Actions Footer */}
              <div className="space-y-2.5 pt-6 border-t border-slate-100">
                {selectedPost.status === 'REVIEW' && (
                  <Button variant="primary" className="w-full text-xs font-bold py-3">
                    Approve Post
                  </Button>
                )}
                <Button variant="outline" className="w-full text-xs font-bold py-3 bg-white border-slate-200">
                  Edit Copy
                </Button>
                <Button variant="ghost" className="w-full text-xs font-bold text-red-500 hover:bg-red-50 hover:text-red-600 py-3">
                  Delete Draft
                </Button>
              </div>

            </div>
          </div>
        )}

        {/* Create Post Interactive Modal */}
        {isCreateModalOpen && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            <div className="absolute inset-0 bg-slate-900/20 backdrop-blur-sm" onClick={() => setIsCreateModalOpen(false)}></div>
            <div className="relative w-full max-w-lg bg-white rounded-2xl shadow-2xl p-6 border border-slate-200/50">
              
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2">
                  <Sparkles className="w-4.5 h-4.5 text-brand-indigo" />
                  <h3 className="text-sm font-extrabold text-slate-800">Generate New Post Outline</h3>
                </div>
                <button 
                  onClick={() => setIsCreateModalOpen(false)}
                  className="p-1 rounded-xl bg-slate-50 text-slate-400 hover:text-slate-600 border border-slate-200 cursor-pointer"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>
              <hr className="border-slate-100 mb-6" />

              <form onSubmit={handleCreatePost} className="space-y-5 text-xs font-semibold text-slate-600">
                
                {/* Platform select */}
                <div className="space-y-2">
                  <span className="text-[10px] font-extrabold text-slate-400 uppercase tracking-widest block">Social Platform</span>
                  <div className="flex gap-3">
                    {['LinkedIn', 'Instagram', 'Facebook'].map(p => (
                      <button
                        key={p}
                        type="button"
                        onClick={() => setNewPostPlatform(p as any)}
                        className={`flex-1 py-3 text-xs font-bold border rounded-xl transition-all cursor-pointer ${
                          newPostPlatform === p 
                            ? 'border-brand-indigo bg-brand-indigo/5 text-brand-indigo shadow-sm' 
                            : 'border-slate-200 hover:bg-slate-50 text-slate-650'
                        }`}
                      >
                        {p}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Topic textarea */}
                <div className="space-y-2">
                  <span className="text-[10px] font-extrabold text-slate-400 uppercase tracking-widest block">What would you like to post about?</span>
                  <textarea 
                    required
                    placeholder="e.g. Write a tip explaining the golden brewing ratio for morning coffee fans..."
                    className="w-full text-slate-800 bg-slate-50/50 border border-slate-200 focus:border-brand-indigo/60 focus:bg-white rounded-xl text-xs p-3 focus:outline-none focus:ring-4 focus:ring-brand-indigo/5 transition-all min-h-[100px]"
                    value={newPostTopic} 
                    onChange={(e) => setNewPostTopic(e.target.value)} 
                  />
                </div>

                <div className="flex gap-2 pt-2">
                  <Button 
                    type="button" 
                    variant="outline" 
                    className="flex-1 bg-white border-slate-200 text-xs py-2.5 font-bold"
                    onClick={() => setIsCreateModalOpen(false)}
                  >
                    Cancel
                  </Button>
                  <Button 
                    type="submit" 
                    variant="primary" 
                    className="flex-1 text-xs py-2.5 font-bold gap-1.5"
                  >
                    <Sparkles className="w-4 h-4" />
                    <span>Generate Post Draft</span>
                  </Button>
                </div>

              </form>

            </div>
          </div>
        )}

      </div>
    </DashboardShell>
  );
}
